sched/deadline: fix some build errors
kernel/sched/deadline.c: In function 'replenish_dl_entity':
kernel/sched/deadline.c:140:4: error: implicit declaration of function 'printk_sched' [-Werror=implicit-function-declaration]
    printk_sched("sched: DL replenish lagged to much\n");
    ^~~~~~~~~~~~

This is because of commit 3984bb13c8f5f2f192aed228a88696d4a697a435, "printk: rename printk_sched to printk_deferred".

kernel/sched/deadline.c: In function 'enqueue_task_dl':
kernel/sched/deadline.c:487:2: error: implicit declaration of function 'inc_nr_running' [-Werror=implicit-function-declaration]
  inc_nr_running(rq);
  ^~~~~~~~~~~~~~
kernel/sched/deadline.c: In function 'dequeue_task_dl':
kernel/sched/deadline.c:500:2: error: implicit declaration of function 'dec_nr_running' [-Werror=implicit-function-declaration]
  dec_nr_running(rq);
  ^~~~~~~~~~~~~~

These two errors are a result of commit 32b1b2b52821cfd49f3e4edfc16502fccc214c3b, "sched, nohz: Change rq->nr_running to always use wrappers", where inc_nr_running and dec_nr_running were changed into add_nr_running and sub_nr_running respectively. I did not have this scheduler at the time so it was not relevant.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Joe Maples <joe@frap129.org>